name: Bulwark CI

on:
  push:
    branches:
    tags:
  pull_request:
    branches:
      - master

jobs:
  lint_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: "2.8.1"
      - uses: actions/checkout@v2

      - name: Lint Checks
        run: lein cljfmt check

      - name: Lein Kibit Check
        run: lein kibit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: "2.8.1"
      - uses: actions/checkout@v2

      - name: Lein clean
        run: lein clean

      - name: Lein deps
        run: lein deps

      - name: Run Tests
        run: lein test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: "2.8.1"
      - uses: actions/checkout@v2

      - name: Calculate Coverage
        run: lein cloverage --output coverage --coveralls --lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy_to_clojars:
    runs-on: ubuntu-latest
    needs:
      [
        lint_check,
        test,
        coverage,
      ]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    env:
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: "2.8.1"
      - uses: actions/checkout@v2

      - name: Deploy to Clojars
        run: lein deploy clojars
